### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by dannyway03** [ksharsha/ADAS#1]
thanks for the nice work! 
I would be curious to have more details on the approach, do you have any description of the algorithm?
Could you share the video/images you used for developing and testing?
Do you really need HoG??

thanks a lot!
-danny

**Comment by ksharsha** [comment]
Hey danny,
Unfortunately the videos I used are confidential and cannot be shared. Regarding the approach what I did was, used optical flow and feature descriptors such as ORB to get an estimate of the moving vehicles. HoG descriptor isn't really necessary however at the beginning this approach would often detect roads as false positives. Using HoG descriptor I was able to overcome it, but by the end after several iterations I was able to avoid that without any HoG descriptor. I will upload a pdf of the approach soon onto my site and let you know once it is done. Let me know if you would like more details.
Thank you!
-Harsha.

**Comment by dannyway03** [comment]
Hi,

thanks for your feedback! would it be possible for you to update the the repo with the latest HOG-free code? Also i really look forward to get more insights from your description.
As far as i understood, you detect moving obstacle by summing up and thresholding the optical flow modulus in each region of interest. Is this correct? 

Also, are you aware of other methods to achieve the same goal?

many thanks!
danny

**Comment by ksharsha** [comment]
Hi,
As of now, I don't think I can update the code but you can just comment out the call to the HoG functions and the init() function and it should work fine. Yes, you are correct, I detect the moving obstacles by thresholding the optical flow modules in each region of interest(obtained using the descriptors) and am not aware of any such methods. Mostly, now-a-days people use CNN's and it of course works very well, however I used this approach(mainly because of lack of data ) and found the results to be quite good.

**Comment by dannyway03** [comment]
Hi again,
i still didn't manage to get how you filter false positives based only on optical flow information..
could you give any hint??
that would be great!
thanks,
d

**Comment by ksharsha** [comment]
Hey,
What I do is I add the optical flow vectors in a region and then use some threshold to determine if that region has any moving obstacle.
